version: '3'

services:
  hpfeedssub:
    build: hpfeedsSub/
    container_name: hpfeedsSub
    networks:
      - quantumlegacy

  hpfeeds:
    image: jc2k/hpfeeds3-broker
    container_name: hpfeeds3
    ports:
      - "0.0.0.0:20000:20000"
    volumes:
      - /opt/Quantum-Legacy/hpfeeds3/broker:/app/var
    networks:
      - quantumlegacy

  elasticsearch:
    build:
      context: docker-elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /opt/Quantum-Legacy/storage/elsticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - quantumlegacy

  logstash:
    build:
      context: docker-elk/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - quantumlegacy
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: docker-elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - quantumlegacy
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
