version: '3'

services:
  cowrie:
    build: ./cowrie
    volumes:
      - ./cowrie/etc/cowrie.cfg:/opt/cowrie/etc/cowrie.cfg
      - cowrie-content:/opt/cowrie/var
    ports:
      - "22:2222"
      - "23:2223"
  
  filebeat:
    build: ./filebeat
    volumes:
      - cowrie-content:/opt/cowrie/var
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml

volumes:
  cowrie-content:./cowrie/var
